import GithubBlogConfig from "@/utills/config/github-blog.config";
const userConfig = GithubBlogConfig({
    title: 'juny.blog',
    description: 'Generated by create next app',
    domain: 'http://localhost:3000',
    githubBlogShowPaths:[{
        path: 'blog'
    }],
    userSitemap: [
        'ads.txt'
    ]
});
export default userConfig;