import { GithubBlogShowPathSrc } from "@/utills/config/config.type";
import GithubBlogConfig from "@/utills/config/github-blog.config";
const userConfig = GithubBlogConfig({
    title: 'juny.blog',
    description: 'Generated by create next app',
    domain: 'http://localhost:3000',
    git: {
        repository: 'Obsidian',
        owner: 'jun-young1993'
    },
    githubBlogShowPaths:[{
        type: 'profile',
        src: GithubBlogShowPathSrc.GIT_AVATAR,
        path: 'jun-young1993' // git repository name
    },{
        type: 'contents',
        path: 'blog'
    },{
        type: 'contents',
        path: 'blog/Driverse'
    }],
    userSitemap: [
        'ads.txt'
    ]
});
export default userConfig;