import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RootLayoutWrapProvider from "@/components/providers/root-rayout-wrap.provider";
import StyleThemeProvider from "@/components/providers/style-theme.provider";
import {ReactNode} from "react";
import UserDataProvider from "@/components/providers/git.user.data.provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <UserDataProvider>
          <StyleThemeProvider>
            <RootLayoutWrapProvider>
              {children}
            </RootLayoutWrapProvider>
          </StyleThemeProvider>
        </UserDataProvider>
      </body>
    </html>
  );
}
